# Generated by Django 5.0 on 2024-02-08 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_invoices_project_projects_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='app.invoices'),
        ),
    ]
