# Generated by Django 5.0 on 2024-02-08 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_projects_invoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='invoice',
        ),
        migrations.AddField(
            model_name='invoices',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='app.client'),
        ),
        migrations.AddField(
            model_name='invoices',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='app.projects'),
        ),
    ]
