# Generated by Django 5.0 on 2024-02-08 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_projects_invoice_invoices_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoices',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='app.client'),
        ),
        migrations.AlterField(
            model_name='invoices',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='app.projects'),
        ),
    ]
