# Generated by Django 5.0 on 2024-02-08 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_invoices_client_alter_invoices_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead_details',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_details', to='app.projects'),
        ),
    ]
