CREATE_CLIENT_SUCCESSFULLY = "Client created successfully."
ALL_CLIENTS_RETRIEVED_SUCCESSFULLY = "All clients retrieved successfully."
SINGLE_CLIENT_RETRIEVED_SUCCESSFULLY = "Single client retrieved successfully."
UPDATE_CLIENT_SUCCESSFULLY = "Client updated successfully."
DELETE_CLIENT_SUCCESSFULLY = "Client deleted successfully."
CLIENT_NOT_FOUND = "Client not found."
CLIENT_EMAIL_REQUIRED = "Email address  is required."
CLIENT_PASSWORD_REQUIRED = "Password is required."
AUTHENTICATION_SUCCESSFULLY = "Authentication is done  successfully"
PASSWORD_INCORRECT = "Password is incorrect"
TOKEN_EXPIRED = "Token has expired"
TOKEN_REQUIRE = "Require Token"

CREATE_PROJECT_SUCCESSFULLY = "Project created successfully."
ALL_PROJECTS_RETRIEVED_SUCCESSFULLY = "All projects retrieved successfully."
SINGLE_PROJECT_RETRIEVED_SUCCESSFULLY = "Project retrieved successfully."
UPDATE_PROJECT_SUCCESSFULLY = "Project updated successfully."
DELETE_PROJECT_SUCCESSFULLY = "Project deleted successfully."
PROJECT_NOT_FOUND = "Project not found."

CREATE_INVOICE_SUCCESSFULLY = "Invoice created successfully"
ALL_INVOICES_RETRIEVED_SUCCESSFULLY = "All invoices retrieved successfully"
SINGLE_INVOICE_RETRIEVED_SUCCESSFULLY = "Single invoice retrieved successfully"
UPDATE_INVOICE_SUCCESSFULLY = "Invoice updated successfully"
DELETE_INVOICE_SUCCESSFULLY = "Invoice deleted successfully"
INVOICE_NOT_FOUND = "Invoice not found"
DOWNLOAD_INVOICE_SUCCESSFULLY = "Invoice data download successfully."


CREATE_LEAD_SUCCESSFULLY = "Lead created successfully."
UPDATE_LEAD_SUCCESSFULLY = "Lead updated successfully."
DELETE_LEAD_SUCCESSFULLY = "Lead deleted successfully."
ALL_LEADS_RETRIEVED_SUCCESSFULLY = "All leads retrieved successfully."
SINGLE_LEAD_RETRIEVED_SUCCESSFULLY = "Single lead retrieved successfully."
LEAD_NOT_FOUND = "Lead  detail not found."

